const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const element=()=>({attrs:{},style:{},setAttribute(k,v){this.attrs[k]=String(v);}});
const scenes=[element(),element()],reveals=[element(),element()];
const drawing={classList:{add(){},remove(){}},querySelectorAll:s=>({'.residence-scene':scenes,'.reference-reveal':reveals}[s]||[])};
let frame,preferenceChange;
const motion={matches:false,addEventListener:(_e,cb)=>{preferenceChange=cb;}};
const context={document:{querySelector:()=>drawing,hidden:false,addEventListener(){}},matchMedia:()=>motion,requestAnimationFrame:cb=>{frame=cb;return 1;},cancelAnimationFrame(){},IntersectionObserver:class{observe(){}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../static/hero-drawing.js'),'utf8'),context);
frame(0);
assert.equal(reveals[0].attrs.width,'0');
frame(9000);
assert.equal(reveals[0].attrs.width,'350');
frame(18000);
assert.equal(reveals[0].attrs.width,'700');
for(let t=18016;t<22800;t+=16)frame(t);
assert.equal(scenes[1].style.display,'','second artwork starts after first fades');
assert(Number(reveals[1].attrs.width)<100,'second drawing cycle starts');
const template=fs.readFileSync(path.join(__dirname,'../templates/components/hero_drawing.html'),'utf8');
assert.match(template,/hero-plan-3\.png/);
assert.match(template,/hero-plan-4\.png/);
assert(!/drawing-pencil|drawing_pencil/.test(template));
assert(!/residence_drawing|residence_paint/.test(template));
motion.matches=true;preferenceChange();
assert(reveals.every(reveal=>reveal.attrs.width==='700'));
console.log('Passed: two supplied plans alternate through reveal, hold and fade.');
