"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import urllib.parse
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured, ValidationError
from django.core.validators import validate_email

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================================
# SECURITY
# ==========================================================

IS_VERCEL = os.environ.get("VERCEL", "").lower() in {"1", "true", "yes"}
DEVELOPMENT_SECRET_KEY = 'django-insecure-0x@xyibv(-23=(===)o#_ew3s!wz%2htgu5ajh=nfpm4yk=&^k'
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip() or DEVELOPMENT_SECRET_KEY
DEBUG = os.environ.get("DJANGO_DEBUG", "false" if IS_VERCEL else "true").lower() in {"1", "true", "yes"}
if not DEBUG and SECRET_KEY == DEVELOPMENT_SECRET_KEY:
    raise ImproperlyConfigured("Set DJANGO_SECRET_KEY before running with DJANGO_DEBUG=false.")
ALLOWED_HOSTS = [item.strip() for item in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if item.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]
if IS_VERCEL and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = [os.environ.get("VERCEL_URL", "").strip()]
    ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]
CSRF_TRUSTED_ORIGINS = [item.strip() for item in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if item.strip()]


# ==========================================================
# APPLICATION DEFINITION
# ==========================================================

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',

    'Ivory',
]


# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================================================
# URL CONFIGURATION
# ==========================================================

ROOT_URLCONF = 'config.urls'


# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# ==========================================================
# DATABASE
# ==========================================================

database_url = os.environ.get("DATABASE_URL", "").strip()
if database_url:
    parsed_database_url = urllib.parse.urlparse(database_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed_database_url.path.lstrip("/"),
            "USER": urllib.parse.unquote(parsed_database_url.username or ""),
            "PASSWORD": urllib.parse.unquote(parsed_database_url.password or ""),
            "HOST": parsed_database_url.hostname or "",
            "PORT": parsed_database_url.port or 5432,
            "OPTIONS": {"sslmode": "require"} if IS_VERCEL else {},
            "CONN_MAX_AGE": 0,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ==========================================================
# SESSION SETTINGS
# ==========================================================

# A visitor can safely resume a persisted support conversation while the browser
# session remains open. The opaque support session contains no transcript.
SESSION_COOKIE_AGE = int(os.environ.get("IVORY_SESSION_SECONDS", "86400"))

# Refresh the 1-minute session timer whenever
# the user makes a request
SESSION_SAVE_EVERY_REQUEST = True

# Session cookie expires when the browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==========================================================
# STATIC FILES
# ==========================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ==========================================================
# EMAIL
# ==========================================================

# Local development previews email in the console. Explicitly enable SMTP only
# after configuring the company's Gmail / Google Workspace account.
IVORY_EMAIL_MODE = os.environ.get("IVORY_EMAIL_MODE", "console").strip().lower()
IVORY_GMAIL_ADDRESS = os.environ.get("IVORY_GMAIL_ADDRESS", "").strip()

if IVORY_EMAIL_MODE not in {"console", "smtp"}:
    raise ImproperlyConfigured("IVORY_EMAIL_MODE must be 'console' or 'smtp'.")

MAILERS = {"default": {"BACKEND": "django.core.mail.backends.console.EmailBackend"}}

if IVORY_EMAIL_MODE == "smtp":
    gmail_app_password = os.environ.get("IVORY_GMAIL_APP_PASSWORD", "").replace(" ", "")
    if not IVORY_GMAIL_ADDRESS or not gmail_app_password:
        raise ImproperlyConfigured(
            "SMTP requires IVORY_GMAIL_ADDRESS and IVORY_GMAIL_APP_PASSWORD."
        )
    try:
        validate_email(IVORY_GMAIL_ADDRESS)
    except ValidationError as exc:
        raise ImproperlyConfigured("IVORY_GMAIL_ADDRESS must be a valid email address.") from exc
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": "smtp.gmail.com",
                "port": 587,
                "use_tls": True,
                "username": IVORY_GMAIL_ADDRESS,
                "password": gmail_app_password,
                "timeout": 10,
            },
        },
    }


# ==========================================================
# IVORY DESIGN STUDIO - ADMIN CONFIGURATION
# ==========================================================

# Optional server-side chat fallback. No key is needed for the studio FAQs.
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_CHAT_MODEL = os.environ.get("OPENAI_CHAT_MODEL", "gpt-4.1-mini").strip() or "gpt-4.1-mini"

# Durable live support. Redis is required in Compose/production; direct local
# checks can intentionally use the in-memory layer by leaving the URL blank.
CHANNEL_REDIS_URL = os.environ.get("CHANNEL_REDIS_URL", "").strip()
if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [CHANNEL_REDIS_URL], "capacity": 200, "expiry": 60},
        }
    }
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.environ.get("CACHE_REDIS_URL", CHANNEL_REDIS_URL),
        }
    }
else:
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

IVORY_SUPPORT_TIMEOUT_SECONDS = max(30, int(os.environ.get("IVORY_SUPPORT_TIMEOUT_SECONDS", "300")))
IVORY_SUPPORT_RATE_LIMIT = max(1, int(os.environ.get("IVORY_SUPPORT_RATE_LIMIT", "20")))
IVORY_SUPPORT_RATE_WINDOW = max(10, int(os.environ.get("IVORY_SUPPORT_RATE_WINDOW", "60")))
IVORY_SUPPORT_RETENTION_DAYS = max(1, int(os.environ.get("IVORY_SUPPORT_RETENTION_DAYS", "90")))
PRIVATE_SUPPORT_ROOT = Path(os.environ.get("PRIVATE_SUPPORT_ROOT", str(BASE_DIR / "private_support")))
IVORY_SUPPORT_UPLOAD_BYTES = int(os.environ.get("IVORY_SUPPORT_UPLOAD_BYTES", "5242880"))
IVORY_SUPPORT_AUDIO_SECONDS = int(os.environ.get("IVORY_SUPPORT_AUDIO_SECONDS", "120"))
IVORY_TRUST_PROXY_HEADERS = os.environ.get("IVORY_TRUST_PROXY_HEADERS", "false").lower() in {"1", "true", "yes"}

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", CHANNEL_REDIS_URL or "redis://localhost:6379/1")
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_TRACK_STARTED = False
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = {
    "support-timeout-reconciliation": {
        "task": "Ivory.tasks.activate_due_support_conversations",
        "schedule": 30.0,
    },
    "support-resolved-retention": {
        "task": "Ivory.tasks.delete_expired_support_conversations",
        "schedule": 86400.0,
    },
}

JAZZMIN_SETTINGS = {

    # ------------------------------------------------------
    # BRANDING
    # ------------------------------------------------------

    "site_title": "Ivory Design Studio Admin",

    "site_header": "Ivory Design Studio",

    "site_brand": "IVORY",

    "site_logo": 'images/a.svg',

    "login_logo": 'images/a.svg',

    
    

    "welcome_sign": "Welcome to Ivory Design Studio",

    "copyright": "Ivory Design Studio",

    "show_sidebar": True,
    "navigation_expanded": True,


    # ------------------------------------------------------
    # SEARCH
    # ------------------------------------------------------

    "search_model": [
        "Ivory.ContactMessage",
    ],


    # ------------------------------------------------------
    # TOP MENU
    # ------------------------------------------------------

    "topmenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": False,
        },

        {
            "name": "Contact Messages",
            "url": "/admin/Ivory/contactmessage/",
            "permissions": ["Ivory.view_contactmessage"],
        },

        {
            "name": "Live Support",
            "url": "/admin/support/",
            "permissions": ["Ivory.view_supportconversation"],
        },

    ],


    # ------------------------------------------------------
    # USER MENU
    # ------------------------------------------------------

    "usermenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": True,
        },

    ],


    # ------------------------------------------------------
    # SIDE MENU
    # ------------------------------------------------------

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_apps": [],

    "hide_models": [],


    # ------------------------------------------------------
    # UI
    # ------------------------------------------------------

    "show_ui_builder": False,

    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {},


    # ------------------------------------------------------
    # ICONS
    # ------------------------------------------------------

    "icons": {

        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "auth.Group": "fas fa-users",

        "Ivory": "fas fa-building",

        "Ivory.ContactMessage": "fas fa-envelope",

        "Ivory.SupportConversation": "fas fa-comments",

        "Ivory.SupportMessage": "fas fa-comment-dots",

    },


    # ------------------------------------------------------
    # LANGUAGE
    # ------------------------------------------------------

    "language_chooser": False,


    # ------------------------------------------------------
    # MODAL
    # ------------------------------------------------------

    "related_modal_active": True,


    # ------------------------------------------------------
    # CUSTOM CSS / JS
    # ------------------------------------------------------

    "custom_css": "admin/ivory-admin.css",

    "custom_js": "admin/support-notifications.js",

}


# ==========================================================
# JAZZMIN UI TWEAKS
# ==========================================================

JAZZMIN_UI_TWEAKS = {

    "theme": "flatly",

    "dark_mode_theme": "darkly",

    "navbar_small_text": False,

    "footer_small_text": False,

    "body_small_text": False,

    "brand_small_text": False,

    "brand_colour": "navbar-light",

    "accent": "accent-dark",

    "navbar": "navbar-white navbar-light",

    "no_navbar_border": False,

    "navbar_fixed": True,

    "layout_boxed": False,

    "footer_fixed": False,

    "sidebar_fixed": True,

    "sidebar": "sidebar-light-primary",

    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,

    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": False,

    "button_classes": {

        "primary": "btn-primary",

        "secondary": "btn-secondary",

        "info": "btn-info",

        "warning": "btn-warning",

        "danger": "btn-danger",

        "success": "btn-success",

    },

    "actions_sticky_top": True,
}


# ==========================================================
# MEDIA FILES
# ==========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Vercel deployments are read-only. Store new public admin uploads in Vercel
# Blob while continuing to serve the media files already bundled in the repo.
if IS_VERCEL:
    STORAGES = {
        "default": {"BACKEND": "Ivory.storage.VercelBlobStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
