# Generated by Django 6.1 on 2026-08-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
