# Generated by Django 6.1 on 2026-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0004_aboutcompany_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='popup_ads/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Popup Advertisement',
                'verbose_name_plural': 'Popup Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
