# Generated by Django 6.1 on 2026-08-30 18:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_business_information(apps, schema_editor):
    BusinessInformation = apps.get_model('Ivory', 'BusinessInformation')
    BusinessInformation.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0006_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('pricing_mode', models.CharField(choices=[('quote_only', 'Quote only — no automatic estimates'), ('per_sq_ft', 'Estimate = rate × stated floor area in square feet')], default='quote_only', max_length=20)),
                ('pricing_guidance', models.TextField(default='Pricing depends on the project scope and specifications. Please use the Contact form for a tailored quote.', help_text='Public pricing notes, exclusions, or quote-only guidance. No secrets.', max_length=400)),
                ('currency', models.CharField(blank=True, help_text='Required for estimates. Enter your actual billing currency, e.g. NPR.', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Enter a three-letter uppercase currency code, e.g. NPR.')])),
                ('rate_per_sq_ft', models.DecimalField(blank=True, decimal_places=2, help_text='Owner-approved rate for one square foot of floor area. No rate is assumed.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pricing_scope', models.CharField(blank=True, help_text='Required for estimates: explain exactly what the rate covers, including tax/exclusions where relevant.', max_length=180)),
                ('location', models.CharField(blank=True, default='Kathmandu, Nepal', help_text='Public studio address/location. The default is only the city already published on the site.', max_length=240)),
                ('nearby_landmark', models.CharField(blank=True, help_text='Verified nearby landmark only; leave blank if unknown.', max_length=180)),
                ('appointment_instructions', models.TextField(default='Use the Contact form with your name, email, phone number, and project details to request a consultation. The team will confirm availability.', max_length=400)),
                ('appointment_url', models.URLField(blank=True, help_text='Optional public booking page. Without it, visitors use /contact/. The chat never confirms a booking.', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat business information',
                'verbose_name_plural': 'Chat business information',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ivory_business_singleton'), models.CheckConstraint(condition=models.Q(('rate_per_sq_ft__isnull', True), ('rate_per_sq_ft__gt', 0), _connector='OR'), name='ivory_business_positive_rate')],
            },
        ),
        migrations.CreateModel(
            name='BusinessSocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('x', 'X / Twitter')], max_length=20)),
                ('handle', models.CharField(blank=True, help_text='The verified public handle, e.g. @youractualhandle. Leave blank if using a URL only.', max_length=80)),
                ('url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='Ivory.businessinformation')),
            ],
            options={
                'verbose_name': 'Public social profile',
                'ordering': ['platform'],
                'constraints': [models.UniqueConstraint(fields=('business', 'platform'), name='ivory_one_social_per_platform')],
            },
        ),
        migrations.RunPython(seed_business_information, migrations.RunPython.noop),
    ]
