# Generated by Django 6.1 on 2026-09-02 16:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0007_business_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_key', models.CharField(db_index=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for staff'), ('bot_handled', 'Automated assistant'), ('human_active', 'Staff handling'), ('resolved', 'Resolved')], db_index=True, default='waiting', max_length=20)),
                ('handoff_state', models.CharField(choices=[('waiting', 'Waiting for a team member'), ('assistant', 'Automated assistant'), ('staff', 'Staff member')], default='waiting', max_length=20)),
                ('lead_state', models.CharField(choices=[('not_started', 'Not started'), ('awaiting_name', 'Waiting for name'), ('awaiting_phone', 'Waiting for phone'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('visitor_name', models.CharField(blank=True, max_length=80)),
                ('visitor_phone', models.CharField(blank=True, max_length=24, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use an international number such as +9779812345678.')])),
                ('staff_unread_count', models.PositiveIntegerField(default=0)),
                ('visitor_unread_count', models.PositiveIntegerField(default=0)),
                ('bot_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('handoff_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('first_staff_reply_at', models.DateTimeField(blank=True, null=True)),
                ('bot_takeover_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('visitor', 'Visitor'), ('staff', 'Staff'), ('assistant', 'Automated assistant'), ('system', 'System')], max_length=12)),
                ('client_message_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('body', models.TextField(max_length=1800)),
                ('read_by_staff', models.BooleanField(default=False)),
                ('read_by_visitor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='Ivory.supportconversation')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', 'last_activity_at'], name='ivory_support_status_activity'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['visitor_key', 'status'], name='ivory_support_visitor_status'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ivory_support_message_time'),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='ivory_support_message_sequence'),
        ),
    ]
