# Generated by Django 6.1 on 2026-09-03 03:08

import Ivory.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0008_supportconversation_supportmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField(max_length=1400)),
                ('aliases', models.TextField(blank=True, help_text='Alternative complete questions, one per line. Avoid generic single words.', max_length=1500)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Custom chat FAQ',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=Ivory.models.private_support_storage, upload_to=Ivory.models.support_upload_path)),
                ('filename', models.CharField(max_length=120)),
                ('content_type', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Ivory.supportmessage')),
            ],
        ),
    ]
