# Generated by Django 6.1 on 2026-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0011_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(max_length=500, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='popupad',
            name='image',
            field=models.ImageField(max_length=500, upload_to='popup_ads/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teamportfolio',
            name='image',
            field=models.ImageField(max_length=500, upload_to='team/portfolio/'),
        ),
    ]
