# Generated by Django 6.1 on 2026-09-05 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0013_projectimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamportfolio',
            name='portfolio_pdf',
            field=models.FileField(blank=True, help_text='Optional PDF portfolio. Upload PDF files only.', max_length=500, upload_to='team/portfolio/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
