# Generated by Django 6.1 on 2026-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0014_teamportfolio_portfolio_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamportfolio',
            name='portfolio_pdf',
            field=models.URLField(blank=True, help_text='Uploaded PDF URL. Use the PDF chooser in the admin form.', max_length=500),
        ),
    ]
