# Generated by Django 6.1 on 2026-09-05 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0015_alter_teamportfolio_portfolio_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Visitor session',
                'verbose_name_plural': 'Visitor sessions',
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website statistics',
                'verbose_name_plural': 'Website statistics',
            },
        ),
    ]
