# Generated by Django 6.1 on 2026-09-08 18:44

import Ivory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0016_activevisitor_sitestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportattachment',
            name='file',
            field=models.FileField(max_length=500, storage=Ivory.models.private_support_storage, upload_to=Ivory.models.support_upload_path),
        ),
    ]
