# Generated by Django 6.1 on 2026-09-30 16:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0028_teammember_category_and_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client invoice counter',
                'verbose_name_plural': 'Client invoice counters',
            },
        ),
        migrations.CreateModel(
            name='ClientProjectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_location', models.CharField(max_length=240)),
                ('project_started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Project amount (NPR)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client project account',
                'verbose_name_plural': 'Client project accounts',
                'ordering': ['-project_started_on', 'client_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('invoice_year', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('invoice_sequence', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Ivory.clientprojectaccount')),
            ],
            options={
                'verbose_name': 'Client payment invoice',
                'verbose_name_plural': 'Client payment invoices',
                'ordering': ['-paid_on', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('invoice_year', 'invoice_sequence'), name='unique_client_project_payment_invoice_number')],
            },
        ),
    ]
