# Generated by Django 6.1 on 2026-09-30 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0029_clientinvoicecounter_clientprojectaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='attendance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='attendance_leave_units',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='attendance_present_days',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='attendance_working_days',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('attendance_type', models.CharField(choices=[('present', 'Present'), ('half_day_leave', 'Half-day leave'), ('full_day_leave', 'Full-day leave')], default='present', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Ivory.teammember')),
            ],
            options={
                'verbose_name': 'Member attendance',
                'verbose_name_plural': 'Member attendance',
                'ordering': ['-attendance_date', 'member__name'],
                'constraints': [models.UniqueConstraint(fields=('member', 'attendance_date'), name='unique_member_attendance_date')],
            },
        ),
    ]
