# Generated by Django 6.1 on 2026-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0030_salaryrecord_attendance_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entry time'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exit time'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='attendance_worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7),
        ),
    ]
