# Generated by Django 6.1 on 2026-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivory', '0031_attendancerecord_check_in_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='video', max_length=5)),
                ('background_image', models.URLField(blank=True, max_length=500)),
                ('background_video', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage hero background',
                'verbose_name_plural': 'Homepage hero background',
            },
        ),
    ]
